/******************************************************************************
 * Copyright (c) 2024 MichaelLynnCSU
 * All Rights Reserved
 *
 * \file    board_compat.h
 * \author  MichaelLynnCSU
 * \date    01-01-2024
 *
 * \brief   Compatibility shim between CubeMX-generated ISR stubs and the
 *          refactored dashboard modules.
 *
 * \details stm32f4xx_it.c is auto-generated by STM32CubeMX and references
 *          the original symbol names (LVGL_Tick, huart1). Rather than
 *          modifying the generated file (which gets overwritten on regen),
 *          this header maps the old names to the new ones via macros and
 *          an extern declaration.
 *
 *          Include this header at the top of stm32f4xx_it.c only.
 *
 * TODO: When regenerating with CubeMX, re-add this include to stm32f4xx_it.c.
 ******************************************************************************/

#ifndef INCLUDE_BOARD_COMPAT_H_
#define INCLUDE_BOARD_COMPAT_H_

#include "ui.h"
#include "log.h"
#include "main.h"
#include "trinity_log.h"
#include <stdint.h>

/* LVGL tick — CubeMX calls LVGL_Tick() from SysTick_Handler */
#define LVGL_Tick()  ui_tick()

/* UART handle — CubeMX passes &huart1 to HAL_UART_IRQHandler */
extern UART_HandleTypeDef g_huart1;
#define huart1  g_huart1

/* Route ARM HardFault to trinity handler */
#define HardFault_Handler  trinity_hard_fault_handler

#endif /* INCLUDE_BOARD_COMPAT_H_ */
