#ifndef SEGGER_RTT_CONF_H
#define SEGGER_RTT_CONF_H

#define BUFFER_SIZE_UP    1024
#define BUFFER_SIZE_DOWN  16
#define SEGGER_RTT_MAX_NUM_UP_BUFFERS    1
#define SEGGER_RTT_MAX_NUM_DOWN_BUFFERS  1
#define SEGGER_RTT_PRINTF_BUFFER_SIZE    64

#endif
