CONFIG_CONSOLE=y            # enable console abstraction
CONFIG_SERIAL=y             # serial API (RTT, UART, and USB)
CONFIG_PRINTK=y             # enable printk
CONFIG_LOG=y                # enable logging subsystem
CONFIG_BUILD_OUTPUT_UF2=y   # build UF2 for flashing
CONFIG_DEBUG=y              # debug hooks enabled
